package com.henrymorgandibie.switchyard.iso8583.codec;

import com.henrymorgandibie.switchyard.iso8583.message.IsoMessage;
import com.henrymorgandibie.switchyard.iso8583.message.Mti;
import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Fixed byte/hex fixtures for all eight supported MTIs, plus three supplementary fixtures
 * isolating TRACK2 and BINARY (fixed + LLLVAR) field encoding.
 *
 * <p><strong>Every expected byte sequence below is computed by hand</strong> (bitmap bit
 * arithmetic shown in the comment above each fixture; field bytes are literal ASCII/hex, not
 * generated by calling {@link IsoMessagePacker} or {@link BitmapCodec}). Each fixture asserts
 * two independent things: that {@code pack(build(...))} equals the hand-computed bytes, and
 * that {@code unpack(handComputedBytes)} yields the same field values the fixture was built
 * from. A packer and an unpacker that both had the same bug could still agree with each other -
 * {@code pack(unpack(x)) == x} is deliberately not used as the primary proof anywhere in this
 * file; see {@link IsoMessageRoundTripSupplementaryTest} for that check kept separate and
 * clearly labeled as supplementary.
 *
 * <p>Bitmap bit convention: bit N (1-64 in the primary word, or 1-64 within the secondary word
 * representing DE(64+N)) is the MSB-first bit at byte index (N-1)/8, bit offset (N-1)%8 from
 * the MSB. Byte 0 covers DE1-8, byte 1 covers DE9-16, ..., byte 7 covers DE57-64.
 */
class IsoMessageFixtureTest {

    private static final String PAN = "4111111111111111"; // well-known fake test PAN, 16 digits

    // ---- Fixture 1: 0200 Financial Transaction Request -------------------------------------
    // Present DEs: {2,3,4,7,11,32,41,49}
    // byte0 (DE1-8):   2,3,4,7 -> 64+32+16+2   = 114 = 0x72
    // byte1 (DE9-16):  11      -> 32            = 0x20
    // byte3 (DE25-32): 32      -> 1             = 0x01
    // byte5 (DE41-48): 41      -> 128           = 0x80
    // byte6 (DE49-56): 49      -> 128           = 0x80
    // all other bytes: 0x00
    @Test
    void fixture0200FinancialRequest() {
        IsoMessage message = IsoMessage.builder(Mti.FINANCIAL_REQUEST)
                .numeric(2, PAN)
                .numeric(3, "000000")
                .numeric(4, "000000005000")
                .numeric(7, "0910120000")
                .numeric(11, "000001")
                .numeric(32, "12345")
                .ans(41, "TERM0001")
                .numeric(49, "566")
                .build();

        byte[] expected = ascii("0200" + "7220000100808000"
                + "16" + PAN + "000000" + "000000005000" + "0910120000" + "000001"
                + "05" + "12345" + "TERM0001" + "566");

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);

        IsoMessage unpacked = IsoMessageUnpacker.unpack(expected);
        assertThat(unpacked.mti()).isEqualTo(Mti.FINANCIAL_REQUEST);
        assertThat(unpacked.stringField(2)).isEqualTo(PAN);
        assertThat(unpacked.stringField(3)).isEqualTo("000000");
        assertThat(unpacked.stringField(4)).isEqualTo("000000005000");
        assertThat(unpacked.stringField(7)).isEqualTo("0910120000");
        assertThat(unpacked.stringField(11)).isEqualTo("000001");
        assertThat(unpacked.stringField(32)).isEqualTo("12345");
        assertThat(unpacked.stringField(41)).isEqualTo("TERM0001");
        assertThat(unpacked.stringField(49)).isEqualTo("566");
    }

    // ---- Fixture 2: 0100 Authorization Request ----------------------------------------------
    // Present DEs: {2,3,4,7,11,22,25,32,41,49}
    // byte0 (DE1-8):   2,3,4,7  = 0x72 (as above)
    // byte1 (DE9-16):  11       = 0x20
    // byte2 (DE17-24): 22 -> bit pos (22-1)-16=5 -> 2^(7-5)=4          = 0x04
    // byte3 (DE25-32): 25 -> pos0->128, 32 -> pos7->1, sum=129         = 0x81
    // byte5 (DE41-48): 41       = 0x80
    // byte6 (DE49-56): 49       = 0x80
    @Test
    void fixture0100AuthorizationRequest() {
        IsoMessage message = IsoMessage.builder(Mti.AUTHORIZATION_REQUEST)
                .numeric(2, PAN)
                .numeric(3, "000000")
                .numeric(4, "000000005000")
                .numeric(7, "0910120500")
                .numeric(11, "000002")
                .numeric(22, "051")
                .numeric(25, "00")
                .numeric(32, "12345")
                .ans(41, "TERM0001")
                .numeric(49, "566")
                .build();

        byte[] expected = ascii("0100" + "7220048100808000"
                + "16" + PAN + "000000" + "000000005000" + "0910120500" + "000002"
                + "051" + "00" + "05" + "12345" + "TERM0001" + "566");

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);

        IsoMessage unpacked = IsoMessageUnpacker.unpack(expected);
        assertThat(unpacked.mti()).isEqualTo(Mti.AUTHORIZATION_REQUEST);
        assertThat(unpacked.stringField(22)).isEqualTo("051");
        assertThat(unpacked.stringField(25)).isEqualTo("00");
        assertThat(unpacked.stringField(32)).isEqualTo("12345");
        assertThat(unpacked.stringField(41)).isEqualTo("TERM0001");
    }

    // ---- Fixture 3: 0110 Authorization Response ---------------------------------------------
    // Present DEs: {2,3,4,7,11,22,25,32,38,39,41,49}
    // byte4 (DE33-40): 38 -> pos5->4, 39 -> pos6->2, sum=6              = 0x06
    // (byte0,1,2,3,5,6 as fixture 2)
    @Test
    void fixture0110AuthorizationResponse() {
        IsoMessage message = IsoMessage.builder(Mti.AUTHORIZATION_RESPONSE)
                .numeric(2, PAN)
                .numeric(3, "000000")
                .numeric(4, "000000005000")
                .numeric(7, "0910120500")
                .numeric(11, "000002")
                .numeric(22, "051")
                .numeric(25, "00")
                .numeric(32, "12345")
                .ans(38, "AUTH01")
                .ans(39, "00")
                .ans(41, "TERM0001")
                .numeric(49, "566")
                .build();

        byte[] expected = ascii("0110" + "7220048106808000"
                + "16" + PAN + "000000" + "000000005000" + "0910120500" + "000002"
                + "051" + "00" + "05" + "12345" + "AUTH01" + "00" + "TERM0001" + "566");

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);

        IsoMessage unpacked = IsoMessageUnpacker.unpack(expected);
        assertThat(unpacked.mti()).isEqualTo(Mti.AUTHORIZATION_RESPONSE);
        assertThat(unpacked.stringField(38)).isEqualTo("AUTH01");
        assertThat(unpacked.stringField(39)).isEqualTo("00");
    }

    // ---- Fixture 4: 0210 Financial Transaction Response --------------------------------------
    // Present DEs: {2,3,4,7,11,32,38,39,41,49} - fixture 1's fields plus DE38/39.
    // byte3 (DE25-32): 32 only = 0x01 ; byte4 (DE33-40): 38,39 = 0x06
    @Test
    void fixture0210FinancialResponse() {
        IsoMessage message = IsoMessage.builder(Mti.FINANCIAL_RESPONSE)
                .numeric(2, PAN)
                .numeric(3, "000000")
                .numeric(4, "000000005000")
                .numeric(7, "0910120000")
                .numeric(11, "000001")
                .numeric(32, "12345")
                .ans(38, "AUTH02")
                .ans(39, "00")
                .ans(41, "TERM0001")
                .numeric(49, "566")
                .build();

        byte[] expected = ascii("0210" + "7220000106808000"
                + "16" + PAN + "000000" + "000000005000" + "0910120000" + "000001"
                + "05" + "12345" + "AUTH02" + "00" + "TERM0001" + "566");

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);

        IsoMessage unpacked = IsoMessageUnpacker.unpack(expected);
        assertThat(unpacked.mti()).isEqualTo(Mti.FINANCIAL_RESPONSE);
        assertThat(unpacked.stringField(39)).isEqualTo("00");
        assertThat(unpacked.stringField(38)).isEqualTo("AUTH02");
    }

    // ---- Fixture 5: 0400 Reversal Request -----------------------------------------------------
    // Present DEs: {3,4,7,11,32,37,41,49} (no DE2 this time - references original via DE37 RRN)
    // byte0 (DE1-8):  3,4,7 -> 32+16+2 = 50                            = 0x32
    // byte3 (DE25-32): 32 only                                        = 0x01
    // byte4 (DE33-40): 37 -> pos4 -> 2^(7-4)=8                         = 0x08
    @Test
    void fixture0400ReversalRequest() {
        IsoMessage message = IsoMessage.builder(Mti.REVERSAL_REQUEST)
                .numeric(3, "020000")
                .numeric(4, "000000005000")
                .numeric(7, "0910120600")
                .numeric(11, "000003")
                .numeric(32, "12345")
                .ans(37, "RRN000000001")
                .ans(41, "TERM0001")
                .numeric(49, "566")
                .build();

        byte[] expected = ascii("0400" + "3220000108808000"
                + "020000" + "000000005000" + "0910120600" + "000003"
                + "05" + "12345" + "RRN000000001" + "TERM0001" + "566");

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);

        IsoMessage unpacked = IsoMessageUnpacker.unpack(expected);
        assertThat(unpacked.mti()).isEqualTo(Mti.REVERSAL_REQUEST);
        assertThat(unpacked.stringField(37)).isEqualTo("RRN000000001");
        assertThat(unpacked.hasField(2)).isFalse();
    }

    // ---- Fixture 6: 0410 Reversal Response -----------------------------------------------------
    // Present DEs: {3,4,7,11,32,37,39,41,49}
    // byte4 (DE33-40): 37 -> 8, 39 -> pos6 -> 2, sum=10                = 0x0A
    @Test
    void fixture0410ReversalResponse() {
        IsoMessage message = IsoMessage.builder(Mti.REVERSAL_RESPONSE)
                .numeric(3, "020000")
                .numeric(4, "000000005000")
                .numeric(7, "0910120600")
                .numeric(11, "000003")
                .numeric(32, "12345")
                .ans(37, "RRN000000001")
                .ans(39, "00")
                .ans(41, "TERM0001")
                .numeric(49, "566")
                .build();

        byte[] expected = ascii("0410" + "322000010A808000"
                + "020000" + "000000005000" + "0910120600" + "000003"
                + "05" + "12345" + "RRN000000001" + "00" + "TERM0001" + "566");

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);

        IsoMessage unpacked = IsoMessageUnpacker.unpack(expected);
        assertThat(unpacked.mti()).isEqualTo(Mti.REVERSAL_RESPONSE);
        assertThat(unpacked.stringField(39)).isEqualTo("00");
    }

    // ---- Fixture 7: 0800 Network Management Request (exercises the SECONDARY bitmap) ---------
    // Present DEs: {7, 11, 70}. DE70 >= 65, so DE1 (secondary-bitmap indicator) is forced on.
    // Primary present bits: {1, 7, 11}
    //   byte0 (DE1-8): 1 -> 128, 7 -> 2, sum=130                        = 0x82
    //   byte1 (DE9-16): 11 -> 32                                       = 0x20
    // Secondary bitmap covers DE65-128; secondary position = DE-64, so DE70 -> position 6.
    //   secondary byte0 (positions 1-8 = DE65-72): position 6 -> pos5 -> 2^(7-5)=4  = 0x04
    @Test
    void fixture0800NetworkManagementRequestUsesSecondaryBitmap() {
        IsoMessage message = IsoMessage.builder(Mti.NETWORK_MANAGEMENT_REQUEST)
                .numeric(7, "0910120700")
                .numeric(11, "000004")
                .numeric(70, "001")
                .build();

        byte[] expected = ascii("0800"
                + "8220000000000000"   // primary bitmap: bits 1,7,11
                + "0400000000000000"   // secondary bitmap: bit 6 (DE70)
                + "0910120700" + "000004" + "001");

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);

        IsoMessage unpacked = IsoMessageUnpacker.unpack(expected);
        assertThat(unpacked.mti()).isEqualTo(Mti.NETWORK_MANAGEMENT_REQUEST);
        assertThat(unpacked.hasField(1)).isFalse(); // DE1 is a bitmap indicator, never a data element itself
        assertThat(unpacked.stringField(70)).isEqualTo("001");
        assertThat(unpacked.stringField(7)).isEqualTo("0910120700");
        assertThat(unpacked.stringField(11)).isEqualTo("000004");
    }

    // ---- Fixture 8: 0810 Network Management Response (also exercises the secondary bitmap) ----
    // Present DEs: {7, 11, 39, 70}
    // Primary: byte0 = 1,7 = 0x82 ; byte1 = 11 = 0x20 ; byte4 (DE33-40): 39 -> pos6 -> 2 = 0x02
    // Secondary: same as fixture 7, bit 6 (DE70) = 0x04
    @Test
    void fixture0810NetworkManagementResponseUsesSecondaryBitmap() {
        IsoMessage message = IsoMessage.builder(Mti.NETWORK_MANAGEMENT_RESPONSE)
                .numeric(7, "0910120700")
                .numeric(11, "000004")
                .ans(39, "00")
                .numeric(70, "001")
                .build();

        byte[] expected = ascii("0810"
                + "8220000002000000"
                + "0400000000000000"
                + "0910120700" + "000004" + "00" + "001");

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);

        IsoMessage unpacked = IsoMessageUnpacker.unpack(expected);
        assertThat(unpacked.mti()).isEqualTo(Mti.NETWORK_MANAGEMENT_RESPONSE);
        assertThat(unpacked.stringField(39)).isEqualTo("00");
        assertThat(unpacked.stringField(70)).isEqualTo("001");
    }

    // ---- Supplementary fixture: TRACK2 (DE35) through the full pack/unpack pipeline -----------
    // Present DEs: {11, 35}
    // byte1 (DE9-16): 11 = 0x20 ; byte4 (DE33-40): 35 -> pos2 -> 2^(7-2)=32 = 0x20
    @Test
    void track2FieldThroughFullPipeline() {
        String track2 = PAN + "=2912101";
        IsoMessage message = IsoMessage.builder(Mti.FINANCIAL_REQUEST)
                .numeric(11, "000005")
                .track2(35, track2)
                .build();

        byte[] expected = ascii("0200" + "0020000020000000" + "000005" + "24" + track2);

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);
        assertThat(IsoMessageUnpacker.unpack(expected).stringField(35)).isEqualTo(track2);
    }

    // ---- Supplementary fixture: fixed BINARY (DE52) through the full pipeline -----------------
    // Present DEs: {11, 52}. byte6 (DE49-56): 52 -> pos3 -> 2^(7-3)=16 = 0x10
    // DE52 value is entirely synthetic, not a real PIN block.
    @Test
    void fixedBinaryFieldThroughFullPipeline() {
        byte[] pin = {0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, (byte) 0x88};
        IsoMessage message = IsoMessage.builder(Mti.FINANCIAL_REQUEST)
                .numeric(11, "000007")
                .binary(52, pin)
                .build();

        byte[] expected = concat(ascii("0200" + "0020000000001000" + "000007"), pin);

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);
        assertThat(IsoMessageUnpacker.unpack(expected).rawField(52)).isEqualTo(pin);
    }

    // ---- Supplementary fixture: LLLVAR BINARY (DE55) through the full pipeline ----------------
    // Present DEs: {11, 55}. byte6 (DE49-56): 55 -> pos6 -> 2^(7-6)=2 = 0x02
    // DE55 value is a synthetic opaque blob, not real ICC/EMV data.
    @Test
    void variableLengthBinaryFieldThroughFullPipeline() {
        byte[] icc = {0x6F, 0x1A, 0x02};
        IsoMessage message = IsoMessage.builder(Mti.FINANCIAL_REQUEST)
                .numeric(11, "000006")
                .binary(55, icc)
                .build();

        byte[] expected = concat(ascii("0200" + "0020000000000200" + "000006" + "003"), icc);

        assertThat(IsoMessagePacker.pack(message)).isEqualTo(expected);
        assertThat(IsoMessageUnpacker.unpack(expected).rawField(55)).isEqualTo(icc);
    }

    private static byte[] ascii(String s) {
        return s.getBytes(StandardCharsets.US_ASCII);
    }

    private static byte[] concat(byte[] a, byte[] b) {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        out.writeBytes(a);
        out.writeBytes(b);
        return out.toByteArray();
    }
}
